name: PHP

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        name: Coding Standards, Tests, and Coverage
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.3'
                  extensions: mbstring, xml, bcmath, pcov
                  coverage: pcov

            - name: Install dependencies
              run: composer install --no-interaction --prefer-dist

            - name: Run standards check
              run: composer run standards:check

            - name: Run tests with 100% coverage
              run: composer run test:coverage
